### ISSUE TITLE
chore: 재생화면 동작 개선

### ISSUE THREAD

**Issue by chopmozzi** [boostcampwm2023/iOS09-Layover#163]
## 💡 issue
재생화면 동작을 개선 한다.

## 📝 todo
- [x] collectionView cell 사이에 생기는 여백 파악하기
- [x] 수정하기
- [x] 셀이 내비바에도 보이도록 하기
- [x] 무한스크롤 시 텔레포트를 위한 셀은 그냥 동영상 로드 안 해버리기
- [x] Slider cell에서 collectionView로 빼기
