### ISSUE TITLE
refactor: 스웨거 성공 응답 상수화

### ISSUE THREAD

**Issue by hw-ani** [boostcampwm2023/iOS09-Layover#169]
## 💡 issue
- 성공 응답을 처리하는 스웨거를 상수화해서 간결하게 표현한다.

## 📝 todo
- [x] Oauth 스웨거 정리
- [x] Member 스웨거 정리
- [x] Report 스웨거 정리
