### ISSUE TITLE
feat: custom exception 설정

### ISSUE THREAD

**Issue by whipbaek** [boostcampwm2023/iOS09-Layover#20]
## 💡 issue

상태코드로는  다양한 상황에 대한 에러를 클라이언트에서 식별하기 힘들다고 생각했음.
따라서 exception이 발생했을 때는 custom한 exception을 응답해주기로 함.
- customCode라는 부분을 활용하여 어떤 상황인지 파악 빨리할 수 있을거라 생각.

응답 예시>

![image](https://github.com/boostcampwm2023/iOS09-Layover/assets/75191916/0e990104-1b10-4fd2-bb8c-dd347a4dac35)

- data 부분은 optional로 필요할 시 넣도록 설정

## 📝 todo
- [x] custom exception 설정
- [x] ts-jenum을 활용하여 custom exception 생성해주기
- [x] 관련 테스트 코드 작성하기
