### ISSUE TITLE
test: Home Scene 테스트 코드 작성

### ISSUE THREAD

**Issue by loinsir** [boostcampwm2023/iOS09-Layover#200]
## 💡 issue
제가 맡았던 Home Scene에 대한 테스트코드를 작성하겠습니다.
아마 CleanStore에 있는 코드를 참고해서 개발할 것 같아요

## 📝 todo
- [x] HomeInteractor 테스트코드 작성
- [x] HomeWorker 테스트코드 작성
- [x] HomePresenter 테스트코드 작성
