### ISSUE TITLE
chore: 각종 문제점 개선

### ISSUE THREAD

**Issue by chopmozzi** [boostcampwm2023/iOS09-Layover#289]
## 💡 issue
썸네일 로드로 인한 재생화면 로딩 문제
프로필 이미지 찌부 문제
프로필 <-> 재생 관련 버그 픽스
신고 실패 확인

## 📝 todo
- [ ] 썸네일 로드 부분 빼버리기
- [ ] asyncCompactMap빼버리기
- [ ] 프로필 찌부 문제 수정하기
- [ ] 프로필 재생 버그 픽스
- [ ] 신고 실패 문제 확인하고 픽스
