### ISSUE TITLE
bug: 릴리즈를 하면서 찾은 버그들 수정

### ISSUE THREAD

**Issue by chopmozzi** [boostcampwm2023/iOS09-Layover#362]
## 🐞 버그 설명
위치 데이터가 업로드 시 적용 안되는 버그
신고 화면 팝업이 안뜨는 버그
릴리즈 버전을 15로 낮추면서 생긴 17에서만 쓰이는 코드 수정

## 📝 todo
- [ ] 위치 데이터가 업로드 시에도 들어갈 수 있도록
- [ ] 신고 화면 팝업이 제대로 동작하도록
- [ ] 릴리즈 버전 호환성 문제를 해결하도록

**Comment by loinsir** [comment]
수정해줘~

**Comment by chopmozzi** [comment]
이거 수정 했던걸로... 기억... 합니다.. 이슈 닫을게요

**Comment by chopmozzi** [comment]
https://github.com/boostcampwm2023/iOS09-Layover/pull/363
