### ISSUE TITLE
feat: 메인 탭바 설정

### ISSUE THREAD

**Issue by loinsir** [boostcampwm2023/iOS09-Layover#8]
## 💡 issue
메인 탭바를 설정하고 로그인 Scene을 생성해놓겠습니다.

## 📝 todo
- [x] 로그인 Scene 생성
- [x] 카카오 SDK 추가
- [x] 로거 추가
- [x] 메인 탭바 간단 설정
