### ISSUE TITLE
Cloud Functoin - 업로드 트리거 & 액션을 설정하고 파이썬 코드를 작성한다.

### ISSUE THREAD

**Issue by whipbaek** [boostcampwm2023/iOS09-Layover#99]
## 💡 issue
presigned url로 original bucket에 업로드 되면 그에 따른 이벤트를 처리한다.

## 📝 todo
- [x] cloud functoin 트리거를 설정한다.
- [x] cloud function 액션을 설정한다.
- [x] 원본 영상 업로딩 callback, 인코딩 요청을 보낸다.
